easy_admin:
    formats:
        date: "d/m/Y"
        time: "H:i"
        datetime: "d/m/Y H:i"
    entities:
        # List the entity class name you want to manage
        Professeur:
            class: App\Entity\Professeur
        Matiere:
            class: App\Entity\Matiere
        Avis:
            class: App\Entity\Avis
        Salle:
            class: App\Entity\Salle
        TypeCours:
            class: App\Entity\TypeCours
        Cours:
            class: App\Entity\Cours
            list:
                - id
                - property: 'dateHeureDebut'
                  label: 'Date heure debut'
                  type: datetime
                - property: 'dateHeureFin'
                  label: 'Date heure fin'
                  type: datetime
                - property: 'type'
                  label: 'Type'
                  type: choice
                  type_options:
                    choices:
                        'TD': 'TD'
                        'TP': 'TP'
                        'Cours': 'Cours'
                - professeur 
                - matiere 
                - salle
