<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHNvjPkq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHNvjPkq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHNvjPkq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHNvjPkq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHNvjPkq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HNvjPkq',
    'container.build_id' => '16da64d9',
    'container.build_time' => 1584440700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHNvjPkq');
