<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1SbmubK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1SbmubK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1SbmubK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1SbmubK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1SbmubK\App_KernelDevDebugContainer([
    'container.build_hash' => '1SbmubK',
    'container.build_id' => 'ece88c6e',
    'container.build_time' => 1584528923,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1SbmubK');
