<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOF6uuPy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOF6uuPy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOF6uuPy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOF6uuPy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOF6uuPy\App_KernelDevDebugContainer([
    'container.build_hash' => 'OF6uuPy',
    'container.build_id' => '9aa272e7',
    'container.build_time' => 1584437481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOF6uuPy');
